t3: 1.0
#####################################
# 対象言語
#####################################
languages:
  - ja_JP
#####################################
# カスタム機能定義
#####################################
info:
  name: aws-core
  customPackage: com.epion_t3.aws.core
  summary:
    - lang: ja_JP
      contents: "AWS系機能をコア部の機能を提供します。"
  description:
    - lang: ja_JP
      contents: "AWS系機能をコア部の機能を提供します。"
#####################################
# 設定定義
#####################################
configurations:


#####################################
# メッセージ定義
#####################################
messages:
