t3: 1.0
#####################################
# 対象言語
#####################################
languages:
  - ja_JP
#####################################
# カスタム機能定義
#####################################
info:
  name: aws-core
  labelName: AWS Core
  customPackage: com.epion_t3.aws.core
  summary:
    - lang: ja_JP
      contents: "AWS系機能をコア部の機能を提供します。"
  description:
    - lang: ja_JP
      contents: "AWS系機能をコア部の機能を提供します。"
#####################################
# 設定定義
#####################################
configurations:
  ####################################
  # SnowflakeConnectionConfiguration
  ####################################
  - id: AwsCredentialsProviderConfiguration
    summary:
      - lang: ja_JP
        contents: "AWSへの接続を行う資格情報の設定です。"
    description:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "AWSへの接続を行う資格情報の設定です。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "アクセスキーIDとシークレットアクセスキーを省略した場合には、環境変数やインスタンス及びコンテナにアタッチされたロールでの解決を試みます。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "詳細は、[AWSのJavaSDKのJavaDoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html) を参照してください。"
      - order: 4
        summary:
          - lang: ja_JP
            contents: "公開範囲の広いリポジトリで管理する場合は、資格のキーとなる情報を記載しないでください。"
    structure:
      - order: 1
        name: configuration
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "「AwsCredentialsProviderConfiguration」固定"
      - order: 2
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 設定のID
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: 設定の概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: 設定の詳細（任意）
      - order: 5
        name: accessKeyId
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "アクセスキーIDを指定します。"
      - order: 6
        name: secretAccessKey
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "シークレットアクセスキーを指定します。"
#####################################
# コマンド定義
#####################################
commands:
#####################################
# メッセージ定義
#####################################
messages: